-- Migration: 0007_telegram_links.sql
-- Description: Telegram notification delivery — wallet <-> chat binding via
--              one-time link codes generated by the site (wallet-auth gated).
-- Created: 2026-07-13

CREATE TABLE IF NOT EXISTS telegram_links (
  wallet_address TEXT PRIMARY KEY,
  chat_id TEXT NOT NULL,
  linked_at INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_telegram_links_chat ON telegram_links(chat_id);

CREATE TABLE IF NOT EXISTS telegram_link_codes (
  code TEXT PRIMARY KEY,
  wallet_address TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT 0,
  used INTEGER NOT NULL DEFAULT 0
);
